require:
  - rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
  TargetRubyVersion: 2.6
  DisplayStyleGuide: true
  ExtraDetails: true

Rails:
  Enabled: true

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
